version: '3.8'

services:
  database:
    image: mysql:5.7
    container_name: crudmysql_database_container
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./database:/data/application
    command: --init-file /data/application/init.sql
    networks:
      - crud_net
    logging:
      driver: none
  web:
    depends_on:
      - database
    # command: sh -c "./wait-for-it.sh -t 0 database:3306 -- npm start"
    build: ./
    container_name: crudmysql_web_container
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=database
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
    - .:/myapp
    networks:
      - crud_net
    links:
      - database
networks:
  crud_net: